// /data/levels.js
const levels = {
  level1: {
    imageSrc: "/img/plateformer/level_one/level.png",
    backgroundSrc: "/img/plateformer/level_one/background.png",
    zones: [
      { x: 10, y: 0, width: 10, height: 1000, collisionType: "solid" },
      { x: 0, y: 237, width: 307, height: 1, collisionType: "solid" },
      {
        x: 300,
        y: 237,
        width: 202,
        height: 2,
        isSlope: true,
        slope: -0.3,
        collisionType: "solid",
      },
      { x: 500, y: 302, width: 155, height: 1, collisionType: "solid" },
      {
        x: 655,
        y: 300,
        width: 200,
        height: 2,
        isSlope: true,
        slope: -0.26,
        collisionType: "solid",
      },
      { x: 850, y: 250, width: 250, height: 20, collisionType: "oneWay" },
      { x: 850, y: 350, width: 250, height: 1, collisionType: "solid" },
      {
        x: 1100,
        y: 350,
        width: 140,
        height: 1,
        isSlope: true,
        slope: -0.26,
        collisionType: "solid",
      },
      { x: 1240, y: 390, width: 500, height: 1, collisionType: "solid" },
      { x: 1300, y: 320, width: 90, height: 1, collisionType: "oneWay" },
      { x: 1500, y: 300, width: 60, height: 1, collisionType: "oneWay" },
      { x: 1390, y: 220, width: 100, height: 1, collisionType: "oneWay" },
      { x: 1540, y: 180, width: 100, height: 1, collisionType: "oneWay" },
      {
        x: 1740,
        y: 390,
        width: 130,
        height: 1,
        isSlope: true,
        slope: -0.2,
        collisionType: "solid",
      },
      {
        x: 1870,
        y: 416,
        width: 90,
        height: 1,
        isSlope: true,
        slope: -0.45,
        collisionType: "solid",
      },
      {
        x: 1960,
        y: 460,
        width: 100,
        height: 1,
        isSlope: true,
        slope: -0.22,
        collisionType: "solid",
      },
      {
        x: 2060,
        y: 480,
        width: 160,
        height: 1,
        isSlope: false,
        collisionType: "solid",
      },
      {
        x: 2220,
        y: 478,
        width: 100,
        height: 1,
        isSlope: true,
        slope: 0.4,
        collisionType: "solid",
      },
    ],
    enemies: [
      {
        x: 200,
        y: 40,
        width: 40,
        height: 40,
        type: "walker",
        hp: 3,
      },
    ],
    triggers: [
      {
        x: 600,
        y: 300,
        width: 50,
        height: 50,
        action: "read",
        data: {
          text: "This world once held secrets...",
        },
      },
      {
        x: 800,
        y: 300,
        width: 50,
        height: 50,
        action: "change_level",
        data: { to: "level2" },
      },
    ],
  },
  level2: {
    imageSrc: "/img/plateformer/level_two/level.png",
    backgroundSrc: "/img/plateformer/level_two/background.png",
    zones: [
      { x: 10, y: 500, width: 10, height: 1000, collisionType: "solid" },
      { x: 0, y: 600, width: 2000, height: 1, collisionType: "solid" },
    
      { x: 500, y: 302, width: 155, height: 1, collisionType: "solid" },
      {
        x: 655,
        y: 300,
        width: 200,
        height: 2,
        isSlope: true,
        slope: -0.26,
        collisionType: "solid",
      },
      { x: 850, y: 250, width: 250, height: 20, collisionType: "oneWay" },
      { x: 850, y: 350, width: 250, height: 1, collisionType: "solid" },
      {
        x: 1100,
        y: 350,
        width: 140,
        height: 1,
        isSlope: true,
        slope: -0.26,
        collisionType: "solid",
      },
      { x: 1240, y: 390, width: 500, height: 1, collisionType: "solid" },
      { x: 1300, y: 320, width: 90, height: 1, collisionType: "oneWay" },
      { x: 1500, y: 300, width: 60, height: 1, collisionType: "oneWay" },
      { x: 1390, y: 220, width: 100, height: 1, collisionType: "oneWay" },
      { x: 1540, y: 180, width: 100, height: 1, collisionType: "oneWay" },
      {
        x: 1740,
        y: 390,
        width: 130,
        height: 1,
        isSlope: true,
        slope: -0.2,
        collisionType: "solid",
      },
      {
        x: 1870,
        y: 416,
        width: 90,
        height: 1,
        isSlope: true,
        slope: -0.45,
        collisionType: "solid",
      },
      {
        x: 1960,
        y: 460,
        width: 100,
        height: 1,
        isSlope: true,
        slope: -0.22,
        collisionType: "solid",
      },
      {
        x: 2060,
        y: 480,
        width: 160,
        height: 1,
        isSlope: false,
        collisionType: "solid",
      },
      {
        x: 2220,
        y: 478,
        width: 100,
        height: 1,
        isSlope: true,
        slope: 0.4,
        collisionType: "solid",
      },
    ],
  },
};

export default levels;
